spring:
  application.name: proto
  main:
    show-banner: true
server:
     port: 8090
---
spring:
  profiles: local
  main:
    show-banner: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:local;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 123qwe
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibertnate.ddl-auto: create-drop
---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/proto
    username: cafe
    password: cafe
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibertnate.ddl-auto: update